# Generated by Django 3.0.5 on 2020-04-14 11:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cake',
            name='discount',
            field=models.ForeignKey(blank=True, default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.DiscountPercent'),
        ),
        migrations.AlterField(
            model_name='dealoftheday',
            name='endtime',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 15, 5, 1, 56, 267044)),
        ),
        migrations.AlterField(
            model_name='discountpercent',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=0, max_digits=2),
        ),
    ]
