# Generated by Django 3.0.4 on 2020-04-06 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200401_1633'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='images/placeholder.png', upload_to='images/')),
                ('image2', models.ImageField(default='images/placeholder.png', upload_to='images/')),
                ('image3', models.ImageField(blank=True, default='images/placeholder.png', null=True, upload_to='images/')),
            ],
        ),
    ]
