# Generated by Django 3.0.5 on 2020-04-14 12:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200414_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealoftheday',
            name='endtime',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 15, 0, 7, 17, 308780, tzinfo=utc)),
        ),
    ]
