# Generated by Django 3.0.5 on 2020-04-13 12:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200413_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealoftheday',
            name='endtime',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 14, 6, 23, 2, 742696)),
        ),
    ]
