# Generated by Django 3.0.5 on 2020-04-14 12:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200414_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealoftheday',
            name='endtime',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 15, 0, 17, 46, 410137, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='dealoftheday',
            name='item_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d/'),
        ),
    ]
