# Generated by Django 3.0.5 on 2020-04-15 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200415_1827'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['last_updated']},
        ),
    ]
